AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: backend-api to be deployed by sam-api-infra.

Resources:
  BackendApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Backend API built in CloudFormation
      Name: backend-api
      EndPointConfiguration:
        Type:
          - REGIONAL
      StageName: HelloWorld
      Policy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/mattbqa-admin                 
            Action: execute-api:Invoke
            Resource:
              - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:backend-api/*

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:

  # CallHelloWorldRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: call-hello-world-role
  #     Description: Role for me to call the hello-world endpoint from the cli
  #     AssumePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/mattbqa-admin                
  #           Action: sts:AssumeRole
  #     Policies: 
  #       - PolicyName: invoke-api
  #         PolicyDocument: 
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action: execute-api:Invoke
  #               Resource: 
  #                 - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:backend-api/*



 

