name: Backend API post merge workflow
run-name: Backend API post merge workflow
on:
  push:
    branches:
      - main
    paths:
      - template.yaml
      - .github/workflows/backend-api-post-merge.yml

  workflow_dispatch:

permissions: 
  id-token: write # This requests the jwt
  contents: read  # This is required for the actions/checkout

jobs:
  build-and-push-sam-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend-api
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2 
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check sam cli version
        run: |
          sam --version

      - name: Run SAM Build on backend-api template
        run: |
          sam build

      - name: Validate and lint backend-api templete        
        run: |
          sam validate --lint

      # - name: check current directory and files within
      #   run: | 
      #     pwd     
      #     ls 

      - name: Upload SAM template to S3
        run: |
          aws s3 cp ./.aws-sam s3://${{  secrets.SAM_ARTIFACT_STORAGE_BUCKET_NAME  }}
